#!/usr/bin/env fish

set --universal fish_greeting ""
set -g fish_prompt_pwd_dir_length 10

function git_prompt
    set BRANCH (git rev-parse --abbrev-ref HEAD 2>/dev/null)
    if [ $status -eq 0 ]
        git diff --cached --exit-code > /dev/null
        if [ $status -eq 0 ]
            set_color normal
            echo -n " ["
            set_color green
            echo -n $BRANCH
            set_color normal
            echo -n "]"
            set_color blue
            echo -n " "
        else
            set_color normal
            echo -n " ["
            set_color red
            echo -n $BRANCH
            set_color normal
            echo -n "]"
            set_color blue
            echo -n " "
        end
    else
        echo -n ""
    end
end

function exit_status_prompt
    set OLD_EXIT_STATUS $argv

    if [ $OLD_EXIT_STATUS -ne 0 ]
        set_color normal
        echo -n " ("
        set_color red
        echo -n $OLD_EXIT_STATUS
        set_color normal
        echo -n ")"
    else
        echo -n ""
    end
end

function fish_prompt
    set OLD_EXIT_STATUS $status

    set_color normal
    echo -n (date +"%H:%M:%S")
    
    set_color --bold
    echo -n " F "
    set_color normal

    if [ $USER = "root" ]
        set_color red
    else
        set_color green
    end

    echo -n $LOGNAME
    echo -n @
    echo -n (hostname)

    set_color blue

    echo -n " "
    echo -n (prompt_pwd)

    exit_status_prompt $OLD_EXIT_STATUS
    git_prompt

    echo ""

    if [ $USER = "root" ]
        set_color red
        echo -n "#"
    else
        set_color green
        echo -n "%"
    end

    set_color normal

    echo -n " > "
end

source $HOME/.alias