#!/usr/bin/env zsh

autoload -U compinit
compinit
zstyle ":completion:*:*:*:*:*" menu select
zstyle ":completion:*" auto-description "specify: %d"
zstyle ":completion:*" completer _expand _complete
zstyle ":completion:*" format "Completing %d"
zstyle ":completion:*" group-name ""
zstyle ":completion:*" list-colors ""
zstyle ":completion:*" list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ":completion:*" matcher-list "m:{a-zA-Z}={A-Za-z}"
zstyle ":completion:*" rehash true
zstyle ":completion:*" select-prompt %SScrolling active: current selection at %p%s
zstyle ":completion:*" use-compctl false
zstyle ":completion:*" verbose true
zstyle ":completion:*:kill:*" command "ps -u $USER -o pid,%cpu,tty,cputime,cmd"

export HISTSIZE=5000
export HISTFILESIZE=5000
export HISTIGNORE="ls:ll:pwd:clear"
export HISTCONTROL="ignoredups"
export HISTFILE="$HOME/.bash_history"

zmodload zsh/complist
setopt extendedglob
setopt promptsubst
zstyle ":completion:*:*:kill:*:processes" list-colors "=(#b) #([0-9]#)*=36=31"

source ~/.znap/znap/znap.zsh
znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting

setopt correctall

function git_prompt() {
    BRANCH=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
    if [ $? -eq 0 ]
    then
        git diff --cached --exit-code > /dev/null
        if [ $? -eq 0 ]
        then
            print -Pn " %f[%F{green}$BRANCH%f]%F{blue}"
        else
            print -Pn " %f[%F{red}$BRANCH%f]%F{blue}"
        fi
    else
        print -Pn ""
    fi
}

function exit_status_prompt() {
    OLD_EXIT_STATUS=$1

    if [ $OLD_EXIT_STATUS -ne 0 ]
    then
        print -Pn " %f(%F{red}$OLD_EXIT_STATUS%f)"
    else
        print -Pn ""
    fi
}

function precmd() {
    OLD_EXIT_STATUS=$?

    if [ $UID -eq 0 ]
    then
        export PROMPT="%f%* %BZ%b %F{red}%n@%m %F{blue}%~\$(exit_status_prompt $OLD_EXIT_STATUS)$(git_prompt)
%F{red}%#%f > "
    else
        export PROMPT="%f%* %BZ%b %F{green}%n@%m %F{blue}%~\$(exit_status_prompt $OLD_EXIT_STATUS)$(git_prompt)
%F{green}%#%f > "
    fi
}

source $HOME/.alias